name: realtime_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - pip:
      - opencv-python
      - depthai
      - torch==2.8.0
      - torchvision==0.23.0
      - tensorrt
      - pycuda
      - tqdm
      - websockets
      - open3d
      - filterpy
